### ISSUE TITLE
Problem z uruchomieniem pliku z infekcją

### ISSUE THREAD

**Issue by ImLittleDakim** [PSZMAJ/goodeye#3]
Zacznę od pytania co należy wpisać w 
![obraz](https://user-images.githubusercontent.com/111659256/185763097-4d840ad8-f1e2-4864-a5db-c2274516a8ac.png)
i w
![obraz](https://user-images.githubusercontent.com/111659256/185763103-faf9ff8b-80a8-4887-bb45-89a308ab896d.png)
ma to być ip i port telefonu czy kaliego z portem 4444?
plus po zrobieniu pliku i wybrania opcji 08 wyskakuje coś takiego:
![obraz](https://user-images.githubusercontent.com/111659256/185763173-52a8dc01-3235-4eda-8d2d-b8bdfb5c25cd.png)
jak zrobić by to działało?

**Comment by PSZMAJ** [comment]
Cześć,
Tak IP do komunikacji to nasz kali, a port to port do komunikacji - mozesz dac 4444 :) 
Jesteś pewny, że plik jest zrobiony? Z info na zdj widać, że nie ma takiej apki.
